sudo: required

language: node_js

node_js:
  - "7"

services: 
  - docker

env:
  - secure: "VFO0lzwbR169WwsXt7ZVjhrs2YyPnOsG7xjusaG5AZDIS5CdmWOpWBSuvQvAubrP3lRSZD1bnoBMKM1UiNOWLTOydkhOmJGAWuNqdzYnZFbDRSXP+YIECVT5/4Q+B+kVXi+ieSgwnl2yEbs9XNX/X7zfxVfbh+Qs9naj5HXiecCU2DyelbEjH0OfU6jkdFrNi/X2SX1izKgNcGKDuEAmkCW7qN5EX5bd3m9mulVRKswAIdyOlOd76gffYY52TF0bl6uqEhtixd4gIHnZuwCgARWhtniGmbhVK7rpXldaiFw43o6kJYWE0PoGrKUDse2SHSY/ixPeW7iTngysydm0IZIr7+ubXZXhGAHddMly8t1afM3U3/A678pYMZANlSmjuzkyctghcJWjCgDqFWYYDJhjXnRgQie2YUhpV1Dxis0GruED0z4foKe325n18v671UGKv5efoZNJKv2rhPANCRKzuWqkoCeqr1NRlgw1pr7/1iTIGS6+21RljHqE0UPmFP+EEoVYf3pH2IyChKacmquHsp649jcmvEK6ecRWma7VD6pJkUr9VBLP2P3ohZDYF7PB/VPYiOqfmujDTsFYNxLE5mQopxCFZs9MeG5Wyre6sAkqRXf3UpOJJvt8Ei3g7JbSWyA3PxXrVTu+tZ4SaKab0VjsAjM4LH9YLv6IfaQ="
  - secure: "hIyqtL5C7bVYwaLpLHHJ8oIHNfIrKJnhBPRZ2qWeB0ZlhyAW2S1RMjbSGXw4N3Iyxnijby4TP5frNEFQkKKdmeR5Wwh4weZbFFiqyLBq9f2rthzuS7m0cZnDhW3R3oNZwWS4epeClKsYi84rssIoqF27LHBLvZjBNNrZWrU0TIREiiwzwD+GSNSuzp064vocKyjo1IWxCGAcGvecfyb/FvWBNU6SQJdG08lW8iappjwac0g96FyqQLGly1XzNOV1X/ZoQVQ8lqLNrJlGlJYQZenN0t4+r7Xctntt65WCwv2OwoDITK6HxE48FCKHlDKvMtG98YDPlxwIgVYALCCrDwLaNevifVNTqYQ3O9KvyU7FZ+TaZs18ym5caPv1FPxSUAA0UDatVVn/tcKsmrj/fskgL2KHnVjHvNXAR4Wh05L/r/ThMb5MTD0WtVG7DX6dLfqNqErMeaFDGD92eW1QfXtPCh9RMMgm/XNlopbnvhhzY5EaAX3PKbWZ6/W+GjXK7xrawzHsM3ORJCO4ZDoSCMs9tojjoFw+dsLcBq9DAkNBdMr5l72UmDyc9/9rDEDrQ/8XD4/bUnskfA8EPjpJSTrhq/9mViWwkz4f16TKM1MclgYNU8vfEQQGEr9kV3dM7qJGTifF66rss4GjQjDksAETDnXy4gK4VpAlHUmjx/E="

install: 
  - docker-compose up
  - docker ps -a

script:
  - yarn test
