language: node_js

node_js:
  - "7"

# services:
#   - postgresql
#   - redis-server

env:
  DB=postgres
  DB=redis

before_install:
  
install:
  - yarn

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE tests_tmp;' -U postgres; fi"
  - yarn add grunt-cli

script:
  - yarn build-prod
  - grunt pgcreatedb:default
  - yarn test

after_success: 

# or

after_failure:

after_script:

cache: 
  - yarn
  # caches to $HOME/.cache/yarn
