version: "3"
services:
  #redis: image: "redis:alpine"
  postgres:
    image: "postgres:9.6.3-alpine"
    ports:
      - "3031:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  web:
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3030:3030"
    volumes: 
      #mounts from container to host's current dir
      - .:/var/log
    depends_on:
      - postgres
    networks:
      - webnet
      # - redis
networks:
  webnet: