version: "3"
services:
  web:
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3030:3030"
    volumes: 
      #mounts project directory on the host to /public inside the container, to minimize reloading image
      - .:/public
    networks:
      - webnet
    environment:
      - PLACEHOLDER='lalala'
networks:
  webnet: