branch-defaults:
  master:
    environment: Timebox-multi
environment-defaults:
  Timebox-multi:
    branch: null
    repository: null
global:
  application_name: Timebox
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Multi-container Docker
    running on 64bit Amazon Linux/2.7.2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
